#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  shooterEncL,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ShooterEncR,    sensorQuadEncoder)
#pragma config(Motor,  port2,           intakeT,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           shooterL,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftFront,	  tmotorVex393_MC29, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port5,           rightFront,	  tmotorVex393_MC29, openLoop, , reversed, driveLeft, encoderPort, None)
#pragma config(Motor,  port6,           leftRear,		  tmotorVex393_MC29, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port7,           rightRear,    tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, None)
#pragma config(Motor,  port8,           shooterR,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           intakeB,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////
//                                                          												 //
//  Thank You Jordan Kiesel (Team 24 - Bots'N'Stuff) For Providing the X-Drive Code  //
//																																									 //
///////////////////////////////////////////////////////////////////////////////////////
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	wait1Msec(2000);

	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
/*void errorLeft ()
{
motor[leftRear] = 127;
motor[leftFront] = 127;
motor[rightRear] = 100;
motor[rightFront] = 100;
}
void errorRight ()
{
motor[leftRear] = 100;
motor[leftFront] = 100;
motor[rightRear] = 127;
motor[rightFront] = 127;
}*/
void drive(double y, double x, double r)//Some of these might need to be made negative
{
	motor [leftFront] = (x + y + r);
	motor [rightFront] = (x + y - r);
	motor [leftRear] = (-x + y + r);
	motor [rightRear] = (-x + y - r);
}

task autonomous()
{

	drive(-127,0,0);
	wait1Msec(5000);//Test this

	drive(0,0,127);
	wait1Msec(1750);
	motor[shooterL] = motor[shooterR] = 127;
	drive(0,0,0);
	wait1Msec(3000);

	motor[shooterL] = motor[shooterR] = 0;
	drive(0,0,0);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////
void setShooter (int x)
{
	motor[shooterL] = x;
	motor[shooterR] = x;
}
void setIntake (int x)
{
	int i = 127;
	motor[intakeT] = i*x;
	motor[intakeB] = i*x;
}
task usercontrol()
{
	// User control code here, inside the loop

	while(true)
	{

		int shoot = vexRT[Btn8D];
		setShooter(shoot*120);
		int intake = vexRT[Btn5D] - vexRT[Btn5U];
		setIntake(intake);
		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDPos(0, 0);
		displayNextLCDString("VEX Team: 5678N");

		displayLCDPos(1, 0);
		displayNextLCDString("We Have SWAG");

		drive(vexRT[Ch3], vexRT[Ch4], vexRT[Ch1]);
	}
}
