#pragma config(Motor,  port1,           intake,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           conveyer,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftShoot1,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftShoot2,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightShoot1,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightShoot2,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          backRight,     tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int lastMotor = 1;
/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////


	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	void shoot ( float x)
{
	motor [leftShoot1] = x;
	motor [leftShoot2] = x;
	motor [rightShoot1] = x;
	motor [rightShoot2] = x;
}

void intaked (float x)

{
	motor [intake] = x;
	motor [conveyer] = x;
}
void stopper ()
{
	intaked(0);
}

int ballWait = 750;
void repat ()
{
	shoot (76);
	wait1Msec(2000);
	intaked(65);
	wait1Msec(ballWait);
}
task autonomous()
{

	repat();
	stopper();
	repat();
	stopper();
	repat();
	stopper();
	repat();
	wait1Msec(4000);
	shoot(0);
	intaked(0);

}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
//void driveArcade (int y, int x)
//{
//	motor [frontLeft] = motor [backLeft] = (y+x);
//	motor [frontRight] = motor [backRight] = (y-x);
//}
//void shooter (int y)
//{
//	motor [rightShoot1] = motor [leftShoot1] = (y);
//}
//void intake (int x)
//{
//	motor[intake] = motor[conveyer] = x;
//}
//task usercontrol()
//{
//	// User control code here, inside the loop

//	while (true)
//	{
//		driveArcade (vexRT [Ch2],vexRT [Ch1]);
//		shooter (vexRT [Ch3]);
//		int intaker = vexRT[Btn7U];
//		intake(intaker*127);

void drive(float y, float x, float r)//Some of these might need to be made negative
{
	motor [frontLeft] = (x + y + r);
	motor [frontRight] = (x + y - r);
	motor [backLeft] = (-x + y + r);
	motor [backRight] = (-x + y - r);
}
void setIntake (int x, int y)
{
	motor[intake] = motor[conveyer] = x - y;
}
task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................
		int intakeForward = vexRT[Btn5U];
		int intakeBackwards = vexRT[Btn5D];
		float setPoint = 98;
				int window = 25;
		int x = vexRT[Ch3];
		if(abs(x) < window)
			x = 0;
		int y = vexRT[Ch4];
		if(abs(y) < window)
			y = 0;
		int r = vexRT[Ch1];
		int shooting = 1;
		int motorShoot = 0;
		if(abs(r) < window)
			r = 0;
		drive(x, y, r);
		setIntake(intakeForward*127, intakeBackwards*127);
		float scaleFactor = 1.0;
		if (vexRT[Btn7U] == 1){
			setPoint = 98;
			scaleFactor = .90;
		} else if (vexRT[Btn7L] == 1){
			setPoint = 91;
			scaleFactor = .85;
		} else if (vexRT[Btn7R] == 1){
			setPoint = 83;
			scaleFactor = .80;
		} else if (vexRT[Btn7D] == 1){
			setPoint = 78;
			scaleFactor = 0.75;
		} else if (vexRT[Btn8U] == 1){
			setPoint = 73;
			scaleFactor = 0.70;
		} else if (vexRT[Btn8L] == 1){
			setPoint = 68;
			scaleFactor = 0.65;
		} else if (vexRT[Btn8R] == 1){
		  setPoint = 61;
			scaleFactor = 0.60;
		} else if (vexRT[Btn8D] == 1){
		  setPoint = 54;
			scaleFactor = 0.55;
		} else {
			shooting = 0;
		}
		float diffRPM = setPoint - getMotorVelocity(rightShoot1);
		//////////////////////////////////////////////////////////
		/*
		if (shooting && getMotorVelocity(rightShoot1) < setPoint )
		{
			motorShoot = 100 * scaleFactor;
		}
		else if (shooting == 1 && getMotorVelocity(rightShoot1) > setPoint )
		{
			motorShoot = 40 * scaleFactor;
		}
		else if (shooting == 1 && getMotorVelocity(rightShoot1) == setPoint)
		{
			motorShoot = 80 * scaleFactor;
		}
		*/
		if (shooting == 1) {
			motorShoot = scaleFactor*127.0;
		}
		else if(shooting == 0)
		{
			motorShoot = 0;
		}
		motor[leftShoot1] = motor[leftShoot2] = motor[rightShoot1] = motor[rightShoot2] = motorShoot;
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................
	}
}
