#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  shooterEncL,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ShooterEncR,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port4,           rightRear,     tmotorVex393_MC29, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port5,           leftRear,      tmotorVex393_MC29, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port6,           intake1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           shooterL,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           shooterR,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////
//                                                          												 //
//  Thank You Jordan Kiesel (Team 24 - Bots'N'Stuff) For Providing the X-Drive Code  //
//																																									 //
///////////////////////////////////////////////////////////////////////////////////////
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	wait1Msec(2000);

	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
/*void errorLeft ()
{
motor[leftRear] = 127;
motor[leftFront] = 127;
motor[rightRear] = 100;
motor[rightFront] = 100;
}
void errorRight ()
{
motor[leftRear] = 100;
motor[leftFront] = 100;
motor[rightRear] = 127;
motor[rightFront] = 127;
}*/
void drive(int speed)//Some of these might need to be made negative
{	motor [leftFront] = speed;
	motor [rightFront] = -speed;
	motor [leftRear] = speed;
	motor [rightRear] = -speed;
}
void rotateL(int speed)//Test this
{	motor [leftFront] = -speed;
	motor [rightFront] = speed;
	motor [leftRear] = -speed;
	motor [rightRear] = speed;
}
void rotateR(int speed)//Test this
{	motor [leftFront] = speed;
	motor [rightFront] = -speed;
	motor [leftRear] = speed;
	motor [rightRear] = -speed;
}

task autonomous()
{
	drive(65);
	wait1Msec(5000);//Test this

	motor[shooterL] = motor[shooterR] = 127;
	drive(0);
	wait1Msec(3000);

	motor[shooterL] = motor[shooterR] = 0;
	drive(0);
	while(true)
	{
		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDPos(0, 0);
		displayNextLCDString("VEX Team: 5678C");

		displayLCDPos(1, 0);
		displayNextLCDString("Driver:Gilbert M");
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////
void setShooter (int x)
{
motor[shooterL] = motor[shooterR] = x;
}

task usercontrol()
{
	// User control code here, inside the loop

while(true)
{

		int shoot = vexRT[Btn8D];
		setShooter(shoot*127);
		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDPos(0, 0);
		displayNextLCDString("VEX Team: 5678C");

		displayLCDPos(1, 0);
		displayNextLCDString("Driver:Gilbert M");


	motor[leftFront] = vexRT[Ch1] + vexRT[Ch2];
	motor[rightRear] =  vexRT[Ch1] - vexRT[Ch2];
	motor[leftRear] = vexRT[Ch4] + vexRT[Ch3];
	motor[rightFront] =  vexRT[Ch4] - vexRT[Ch3];
}
}
