#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    gyro,           sensorNone)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port4,           rightRear,     tmotorVex393_MC29, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port5,           leftRear,      tmotorVex393_MC29, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port6,           intake1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           shooterL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           shooterR,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	wait1Msec(2000);

	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
/*void errorLeft ()
{
motor[leftRear] = 127;
motor[leftFront] = 127;
motor[rightRear] = 100;
motor[rightFront] = 100;
}
void errorRight ()
{
motor[leftRear] = 100;
motor[leftFront] = 100;
motor[rightRear] = 127;
motor[rightFront] = 127;
}*/
void drive(int speed)//Some of these might need to be made negative
{	motor [leftFront] = speed;
	motor [rightFront] = -speed;
	motor [leftRear] = speed;
	motor [rightRear] = -speed;
}
void rotateL(int speed)//Test this
{	motor [leftFront] = -speed;
	motor [rightFront] = speed;
	motor [leftRear] = -speed;
	motor [rightRear] = speed;
}
void rotateR(int speed)//Test this
{	motor [leftFront] = speed;
	motor [rightFront] = -speed;
	motor [leftRear] = speed;
	motor [rightRear] = -speed;
}
void intake(int speed)
{
	motor[intake1] = motor[intake2] = speed;
}
void shoot(int speed)
{
	motor [shooterL] = motor[shooterR] = speed;
}
void stopAll()
{
	drive(0);
	intake(0);
	shoot(0);
}
task autonomous()
{
	//Old Auton, Keep Until new one is Proven

	/*
	drive(127);
	wait1Msec(7000);//Test this

	motor[shooterL] = motor[shooterR] = 127;
	drive(0);
	wait1Msec(3000);

	motor[shooterL] = motor[shooterR] = 0;
	drive(0);
	*/
	//Adujust Times Below
	//Ball One
	shoot(127);
	wait1Msec(5000);
	intake(127);
	wait1Msec(750);
	intake(0);
	wait1Msec(750);
	//Ball Two
	shoot(127);
	wait1Msec(5000);
	intake(127);
	wait1Msec(750);
	intake(0);
	wait1Msec(750);
	//Ball Three
	shoot(127);
	wait1Msec(5000);
	intake(127);
	wait1Msec(750);
	intake(0);
	wait1Msec(750);
	//Ball Four
	shoot(127);
	wait1Msec(5000);
	intake(127);
	wait1Msec(750);
	intake(0);
	wait1Msec(750);

	stopAll();

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////
void setShooter (int x)
{
	motor[shooterL] = motor[shooterR] = x;
}
void setIntake (int x, int y)
{
	motor[intake1] = motor[intake2] = x - y;
}
task usercontrol()
{
	while(true)
	{

		int shoot = vexRT[Btn7U];
		int intakeForward = vexRT[Btn6U];
		int intakeBackwards = vexRT[Btn6D];
		setShooter(shoot*127);
		setIntake(intakeForward*50, intakeBackwards*50);
		motor[leftFront] = vexRT[Ch1] + vexRT[Ch2];
		motor[rightRear] =  vexRT[Ch1] - vexRT[Ch2];
		motor[leftRear] = vexRT[Ch4] + vexRT[Ch3];
		motor[rightFront] =  vexRT[Ch4] - vexRT[Ch3];
	}
}
